services:
    toxyy.postcomments.listener:
        class: toxyy\postcomments\event\listener
        arguments:
            - '@config'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }